/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyDAO__factory } from "./MyDAO__factory";
export { PolygonDAO__factory } from "./PolygonDAO__factory";
